-- Seed data. Safe to re-run: uses ON CONFLICT DO NOTHING.
--
-- IMPORTANT — READ BEFORE RUNNING:
-- The password_hash values below are PLACEHOLDERS ('*** RUN scripts/hash-password.js ***') and
-- will NOT let anyone log in. This is deliberate: a real bcrypt hash can only be generated by
-- actually running bcrypt, which needs `npm install` first (not available in the sandbox this
-- file was written in). After `npm install` in backend/, run:
--   node scripts/hash-password.js "YourChosenPassword"
-- and paste the printed hash in place of each placeholder below before running this seed file.
-- Change every seeded password immediately after first login in production.

BEGIN;

INSERT INTO users (name, email, password_hash, role) VALUES
  ('Ronald Opio', 'ronald@roplantservices.com', '*** RUN scripts/hash-password.js ***', 'Admin'),
  ('Grace Nabirye', 'grace@roplantservices.com', '*** RUN scripts/hash-password.js ***', 'Manager'),
  ('David Mugisha', 'david@roplantservices.com', '*** RUN scripts/hash-password.js ***', 'Sales'),
  ('Patience Auma', 'patience@roplantservices.com', '*** RUN scripts/hash-password.js ***', 'Inventory'),
  ('Samuel Kato', 'samuel@roplantservices.com', '*** RUN scripts/hash-password.js ***', 'Accountant')
ON CONFLICT (email) DO NOTHING;

INSERT INTO suppliers (name, phone, email, balance) VALUES
  ('Massey Ferguson Parts (U) Ltd', '+256 414 220 019', 'sales@mfparts.example.com', 0),
  ('John Deere East Africa', '+256 414 556 210', 'orders@jdeafrica.example.com', 0),
  ('New Holland Distributors', '+256 312 998 004', 'supply@nhd.example.com', 0),
  ('Generic Auto Spares Kampala', '+256 700 774 552', 'genauto@example.com', 0)
ON CONFLICT DO NOTHING;

INSERT INTO customers (name, phone, email, credit_limit, balance) VALUES
  ('Kigezi Agro Traders', '+256 772 456 123', 'kigezi.agro@example.com', 2000000, 0),
  ('Mbale Farm Equipment Ltd', '+256 701 998 221', 'mbale.fe@example.com', 5000000, 0),
  ('Semanda Wilson (Walk-in)', '+256 782 334 210', '', 0, 0),
  ('Northern Tractor Hub', '+256 758 112 984', 'info@ntractorhub.example.com', 3000000, 0),
  ('Busoga Mechanization Co-op', '+256 793 665 442', 'busoga.coop@example.com', 1500000, 0)
ON CONFLICT DO NOTHING;

INSERT INTO products (sku, part_number, barcode, name, category, brand, compatibility, cost_price, sell_price, stock_qty, reorder_level, max_stock, primary_supplier_id, rack, shelf_bin) VALUES
  ('ENG-0001', 'MF-3610245', '8901234500011', 'Cylinder Head Gasket', 'Engine Parts', 'Massey Ferguson', 'MF 240, MF 375', 85000, 135000, 14, 5, 20, 1, 'A', '1'),
  ('HYD-0002', 'JD-RE12345', '8901234500028', 'Hydraulic Lift Pump', 'Hydraulics', 'John Deere', 'JD 5310, JD 5075E', 420000, 610000, 3, 4, 15, 2, 'A', '2'),
  ('FLT-0003', 'NH-84475542', '8901234500035', 'Oil Filter Cartridge', 'Filters', 'New Holland', 'NH TT75, NH 3630', 12000, 22000, 62, 20, 50, 3, 'S', '1'),
  ('ELE-0004', 'CIH-87654321', '8901234500042', 'Starter Motor 12V', 'Electrical', 'Case IH', 'Case IH 5130, 595', 265000, 390000, 6, 3, 20, 4, 'B', '1'),
  ('TRN-0005', 'MF-1867233M91', '8901234500059', 'Clutch Plate Assembly', 'Transmission', 'Massey Ferguson', 'MF 375, MF 390', 195000, 285000, 9, 4, 25, 1, 'A', '1'),
  ('BRK-0006', 'GEN-BRK-2210', '8901234500066', 'Brake Shoe Set', 'Brakes', 'Generic/Aftermarket', 'Universal - 2WD tractors', 48000, 75000, 24, 10, 30, 4, 'B', '1'),
  ('TYR-0007', 'JD-TYR-1834R', '8901234500073', 'Rear Tyre 18.4-34', 'Tyres & Wheels', 'John Deere', 'JD 5310, JD 5075E', 780000, 1050000, 0, 3, 10, 2, 'A', '2'),
  ('BLT-0008', 'NH-BLT-5540', '8901234500080', 'Fan Belt Set', 'Belts & Chains', 'New Holland', 'NH TT75, NH 4630', 22000, 38000, 41, 15, 35, 3, 'S', '1'),
  ('ENG-0009', 'CIH-INJ-9042', '8901234500097', 'Fuel Injector Nozzle', 'Engine Parts', 'Case IH', 'Case IH 595, 685', 96000, 148000, 17, 6, 25, 4, 'A', '1'),
  ('HYD-0010', 'MF-HYD-7723', '8901234500103', 'Hydraulic Hose 3/4"', 'Hydraulics', 'Massey Ferguson', 'Universal', 18000, 32000, 55, 20, 60, 1, 'B', '1'),
  ('ELE-0011', 'GEN-BAT-12100', '8901234500110', 'Battery 12V 100Ah', 'Electrical', 'Generic/Aftermarket', 'Universal', 310000, 455000, 8, 4, 20, 4, 'S', '1'),
  ('FLT-0012', 'JD-FLT-6620', '8901234500127', 'Air Filter Element', 'Filters', 'John Deere', 'JD 5310, JD 5075E', 16000, 27000, 4, 15, 40, 2, 'S', '1')
ON CONFLICT (sku) DO NOTHING;

-- Opening stock ledger entries for every seeded product
INSERT INTO stock_movements (product_id, type, qty_change, balance_before, balance_after, reference)
SELECT id, 'Opening Stock', stock_qty, 0, stock_qty, 'OPEN-0001' FROM products
WHERE NOT EXISTS (SELECT 1 FROM stock_movements WHERE reference = 'OPEN-0001' AND product_id = products.id);

COMMIT;
